apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: node-app
        image: mitchhamm/kubernetes-workshop:1.0.0
