apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
  type: LoadBalancer
